Feat 347 : Implementação do TypeScript
kauelunelli/VueTypescript pull request #1
Opened 2022-07-21 23:21 UTC by kauelunelli

https://user-images.githubusercontent.com/71523699/180330885-0c79d9ff-77e4-440a-8b54-876107728b25.mp4

2022-07-22 12:30 UTC, dinobergue-viana requested changes
@kauelunelli olhando o seu video, aconteceu aquele problema que a gente tinha conversado. Ao editar um produto no modal, a alteração refletiu imediatamente na listagem.

2022-07-22 12:38 UTC, VitorAlves-Warren commented on typescript-api/src/components/ModalProduct.vue
> +  }
O que é usado no template colocamos como public.
O padrão é esse aqui
<img width="744" alt="Captura de Tela 2022-07-22 às 09 32 07" src="https://user-images.githubusercontent.com/96549586/180440323-0054218f-483f-442c-b195-d5544fd0d8b6.png">

Ai se puder dar uma revisada se está certo em todos os locais

2022-07-22 12:47 UTC, VitorAlves-Warren commented on typescript-api/src/components/messages/MessageSucess.vue
> +  @Prop() readonly msg!: string;
Para prop usamos esse padrão 
<img width="525" alt="Captura de Tela 2022-07-22 às 09 40 48" src="https://user-images.githubusercontent.com/96549586/180442055-c12c720a-9d20-4db4-9678-3138ec538b7d.png">

Passando um objeto dentro do @Prop(), com as propriedades type, required e default caso não seja required

2022-07-22 12:48 UTC, VitorAlves-Warren commented on typescript-api/src/components/types.ts
> +export interface IProduct {
Esse arquivo pode estar em um pasta types, bem parecido com o router, tem uma pasta e dentro o arquivo index.ts

2022-07-22 12:50 UTC, VitorAlves-Warren commented on typescript-api/src/services/product.ts
> +  },
Aqui vc pode colocar um tipo para o retorno, ai vc usaria ele assim.
return http.post<Tipo que criou>("products", product);

2022-07-22 12:55 UTC, dinobergue-viana commented on typescript-api/src/components/ModalProduct.vue
> +        />
@kauelunelli eu penso que seria legal você componentizar esse input, já que ele é repetido várias vezes aqui. Você pode criar um único componente, com variações para atender a qualquer necessidade, ou você pode criar um componente de input para texto, um para dinheiro, outro para numero, etc.

2022-07-22 12:55 UTC, dinobergue-viana commented on typescript-api/src/components/ModalProduct.vue
> +  @Prop() readonly editProduct!: IProduct;
@kauelunelli aqui nessa prop é importante tipa-la e dizer se é obrigatório ou não que o elemento pai a passe.
Seria algo: `@Prop(type: Object, required: true) `.
Isso serve para outras props que você tiver na aplicação.

2022-07-22 13:04 UTC, dinobergue-viana commented on typescript-api/src/components/Navbar.vue
> +      </svg>
Você pode colocar esse `svg` em um diretório específico para esse tipo de arquivo (imagens em geral). Por exemplo, cria um diretório `src/assets`, e dentro de assets criar um arquivo `nome-da-imagem.svg`. Daí, basta usar esse arquivo onde você quiser.

2022-07-22 13:04 UTC, dinobergue-viana commented on typescript-api/src/components/messages/MessageSucess.vue
> +  }
Nesse caso, como a função não retorna algo, você pode deixar ela vazia. Sem o `return`.

2022-07-22 13:56 UTC, kauelunelli commented on typescript-api/src/components/messages/MessageSucess.vue
> +  }
@dinobergue-viana Eu ia deixar ela vazia, porém o vue reclamava que não podia ter uma função vazia

2022-07-22 14:28 UTC, kauelunelli commented on typescript-api/src/components/messages/MessageSucess.vue
> +  }
Unexpected empty method 'closeSucessMessage'  @typescript-eslint/no-empty-function

2022-07-22 14:47 UTC, kauelunelli commented on typescript-api/src/components/types.ts
> +export interface IProduct {
[4bd6c77](https://github.com/kauelunelli/VueTypescript/pull/1/commits/4bd6c77b615a0c1e95960d9684ffd4b7f10acd09)

2022-07-22 18:09 UTC, kauelunelli commented on typescript-api/src/services/product.ts
> +  },
[2b73263](https://github.com/kauelunelli/VueTypescript/pull/1/commits/2b732632d38dd1d1b292b5b1f3e89d4ca0f6db98)

2022-07-22 18:10 UTC, kauelunelli commented on typescript-api/src/components/ModalProduct.vue
> +  @Prop() readonly editProduct!: IProduct;
[2b73263](https://github.com/kauelunelli/VueTypescript/pull/1/commits/2b732632d38dd1d1b292b5b1f3e89d4ca0f6db98)

2022-07-22 18:12 UTC, kauelunelli commented on typescript-api/src/components/messages/MessageSucess.vue
> +  @Prop() readonly msg!: string;
[fefca73](https://github.com/kauelunelli/VueTypescript/pull/1/commits/fefca736064002ba221e3a92d3277bd0bcee6865)

2022-07-22 18:32 UTC, kauelunelli commented on typescript-api/src/components/Navbar.vue
> +      </svg>
[fe8d69e](https://github.com/kauelunelli/VueTypescript/pull/1/commits/fe8d69ecefcc3a57c80c4dc7ef26d49fa3ece378)

2022-07-22 18:34 UTC, kauelunelli commented on typescript-api/src/components/ModalProduct.vue
> +  }
[18a0918](https://github.com/kauelunelli/VueTypescript/pull/1/commits/18a091829ebbe33f57dd60328f41f92643f0d841)

2022-07-22 20:56 UTC, kauelunelli commented
> @kauelunelli olhando o seu video, aconteceu aquele problema que a gente tinha conversado. Ao editar um produto no modal, a alteração refletiu imediatamente na listagem.

[f34c0d4](https://github.com/kauelunelli/VueTypescript/pull/1/commits/f34c0d43b9ab5179796e9eceb1b6a1d7d0c64c18) Consegui!!!

2022-07-25 19:56 UTC, dinobergue-viana approved these changes

2022-07-26 01:55 UTC, merged